# CRAN packages
install.packages("devtools")
install.packages("pkgbuild")
library(devtools)
library(pkgbuild)

devtools::install_version("tidyr", version = "0.8.2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggplot2", version = "3.1.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggrepel", version = "0.8.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggthemes", version = "4.1.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("gplots", version = "3.0.1.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggbeeswarm", version = "0.6.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("reshape2", version = "1.4.3", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("factoextra", version = "1.0.5", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Hmisc", version = "4.2-0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("VennDiagram", version = "1.6.20", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("hexbin", version = "1.27.2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("openxlsx", version = "4.1.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("data.table", version = "1.12.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("scales", version = "1.0.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("tensorflow", version = "1.10", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("dplyr", version = "0.8.0.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("seurat", version = "2.3.4", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)