# CRAN packages
install.packages("devtools")
install.packages("pkgbuild")
library(devtools)
library(pkgbuild)

devtools::install_version("tidyverse", version = "1.3.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("future", version = "1.12.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("future.apply", version = "1.2.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("reticulate", version = "1.16", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("lubridate", version = "1.7.9", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("patchwork", version = "1.0.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("RColorBrewer", version = "1.1-2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("pheatmap", version = "1.0.12", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggrepel", version = "0.8.2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggthemes", version = "4.2.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("gplots", version = "3.0.4", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggbeeswarm", version = "0.6.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("reshape2", version = "1.4.4", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggpubr", version = "0.4.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("factoextra", version = "1.0.7", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Hmisc", version = "4.4-1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("VennDiagram", version = "1.6.20", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("hexbin", version = "1.28.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("openxlsx", version = "4.1.5", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("data.table", version = "1.13.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("scales", version = "1.1.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("tensorflow", version = "2.2.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Matrix.utils", version = "0.9.8", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Matrix", version = "1.2-18", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("R.utils", version = "2.9.2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("useful", version = "1.2.6", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Rmisc", version = "1.5", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("corrplot", version = "0.84", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("UpSetR", version = "1.4.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Seurat", version = "3.2.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("liger", version = "1.1.2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("amap", version = "0.8-18", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("umap", version = "0.2.6.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("fastcluster", version = "1.1.25", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)