library(devtools)
library(pkgbuild)

# Bioconductor packages

BiocManager::install("rhdf5",update=FALSE,ask=FALSE)
devtools::install_version("GSVA", version="1.30.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("GSEABase", version="1.44.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("singscore", version="1.2.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("clusterProfiler", version="3.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DOSE", version="3.8.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("GSEABase", version="1.44.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("RColorBrewer", version="1.1-2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ComplexHeatmap", version="1.20.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("tximport", version="1.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-praoject.org"),upgrade = "never", force = TRUE)
devtools::install_version("DESeq2", version="1.22.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("vsn", version="3.50.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("pheatmap", version="1.0.12", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("genefilter", version="1.64.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("biomaRt", version="2.38.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("limma", version="3.38.3", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("edgeR", version="3.24.3", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("sva", version="3.30.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("IHW", version="1.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ChIPseeker", version="1.18.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ballgown", version="2.14.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("apeglm", version="1.4.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SC3", version="1.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DropletUtils", version="1.2.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("KEGGgraph", version="1.42.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SingleCellExperiment", version="1.4.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SummarizedExperiment", version="1.12.0", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("iSEE", version="1.2.3", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("scater", version="1.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("monocle", version="2.10.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("scran", version="1.10.2", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("zinbwave", version="1.4.1", repos=c("https://bioconductor.org/packages/3.8/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("org.Mm.eg.db", version="3.7.0", repos="https://bioconductor.org/packages/3.8/data/annotation",upgrade = "never", force = TRUE)
devtools::install_version("org.Hs.eg.db", version="3.7.0", repos="https://bioconductor.org/packages/3.8/data/annotation",upgrade = "never", force = TRUE)