# CRAN packages
install.packages("devtools")
install.packages("pkgbuild")
library(devtools)
library(pkgbuild)

devtools::install_version("tidyverse", version = "1.3.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("future", version = "1.12.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("future.apply", version = "1.2.0", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("RColorBrewer", version = "1.1-2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("pheatmap", version = "1.0.12", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggrepel", version = "0.9.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("ggthemes", version = "4.2.4", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("reshape2", version = "1.4.4", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Matrix.utils", version = "0.9.8", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Matrix", version = "1.3-2", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("R.utils", version = "2.10.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("useful", version = "1.2.6", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Rmisc", version = "1.5", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
devtools::install_version("Seurat", version = "4.0.1", repos = "http://cran.us.r-project.org",upgrade = "never", force = TRUE)
