library(devtools)
library(pkgbuild)

# Bioconductor packages

BiocManager::install("rhdf5",update=FALSE,ask=FALSE)
devtools::install_version("BiocGenerics", version="0.32.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DelayedArray", version="0.12.2", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DelayedMatrixStats", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ggbio", version="1.34.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("S4Vectors", version="0.24.1", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("batchelor", version="1.2.4", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("GSVA", version="1.34.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("GSEABase", version="1.48.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("singscore", version="1.6.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("clusterProfiler", version="3.14.3", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DOSE", version="3.12.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ComplexHeatmap", version="2.2.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("tximport", version="1.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-praoject.org"),upgrade = "never", force = TRUE)
devtools::install_version("DESeq2", version="1.26.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("vsn", version="3.54.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("genefilter", version="1.68.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("biomaRt", version="2.42.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("limma", version="3.42.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("edgeR", version="3.28.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("sva", version="3.34.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("IHW", version="1.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ChIPseeker", version="1.22.1", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ballgown", version="2.18.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("apeglm", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SC3", version="1.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DropletUtils", version="1.6.1", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("KEGGgraph", version="1.46.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SingleCellExperiment", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SummarizedExperiment", version="1.16.1", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("iSEE", version="1.6.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("scater", version="1.14.6", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("monocle", version="2.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("scran", version="1.14.5", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("zinbwave", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SCnorm", version="1.8.2", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("MAST", version="1.12.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("BASiCS", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("slingshot", version="1.4.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("scde", version="2.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("TSCAN", version="1.24.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("EnrichmentBrowser", version="2.16.1", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("AUCell", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("fgsea", version="1.12.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("goseq", version="1.38.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("TxDb.Mmusculus.UCSC.mm10.knownGene", version="3.10.0", repos="https://bioconductor.org/packages/3.10/data/annotation",upgrade = "never", force = TRUE)
devtools::install_version("TxDb.Hsapiens.UCSC.hg38.knownGene", version="3.10.0", repos="https://bioconductor.org/packages/3.10/data/annotation",upgrade = "never", force = TRUE)
devtools::install_version("org.Mm.eg.db", version="3.10.0", repos="https://bioconductor.org/packages/3.10/data/annotation",upgrade = "never", force = TRUE)
devtools::install_version("org.Hs.eg.db", version="3.10.0", repos="https://bioconductor.org/packages/3.10/data/annotation",upgrade = "never", force = TRUE)
devtools::install_version("DiffBind", version="2.14.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("chromVAR", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("motifmatchr", version="1.8.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("SingleR", version="1.0.5", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("Rsubread", version="2.0.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("rGREAT", version="1.18.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("multtest", version="2.42.0", repos=c("https://bioconductor.org/packages/3.10/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)