library(devtools)
library(pkgbuild)

# Bioconductor packages
devtools::install_version("clusterProfiler", version="4.0.5", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DOSE", version="3.18.2", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ComplexHeatmap", version="2.8.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("tximport", version="1.20.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("DESeq2", version="1.32.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("vsn", version="3.60.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("biomaRt", version="2.48.3", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("sva", version="3.40.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("IHW", version="1.20.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("apeglm", version="1.14.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SummarizedExperiment", version="1.22.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("TSCAN", version="1.30.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("AUCell", version="1.14.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("LoomExperiment", version="1.10.1", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("SingleR", version="1.6.1", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("Rsubread", version="2.6.4", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("RcisTarget", version="1.12.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("Gviz", version="1.36.2", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("ChIPseeker", version="1.28.3", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)
devtools::install_version("chromVAR", version="1.14.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)
devtools::install_version("motifmatchr", version="1.14.0", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"), upgrade = "never", force = TRUE)